# .github/FUNDING.yml
# These are supported funding model platforms

github: bryanseah234  # Your GitHub Sponsors username
# patreon: # Your Patreon username
# open_collective: # Your Open Collective username
# ko_fi: # Your Ko-fi username
# tidelift: # npm/package-name or pypi/package-name etc
# community_bridge: # Project name on Community Bridge
# liberapay: # Your Liberapay username
# issuehunt: # Your IssueHunt username
# lfx_crowdfunding: # Your LFX Crowdfunding project name
# polar: # Your Polar username
# buy_me_a_coffee: # Your Buy Me a Coffee username
# custom: ["https://your-custom-link.com"]  # Up to 4 custom links
